# Statistic Creation

This notebook is used to create the statistics based on the collected users file.

In [11]:
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
path_users = os.path.join("users_edited.json")
attributes = ["Reputation", "votes", "avotes", "qvotes", "count_of_answers", "count_of_questions"]

In [34]:
def create_histogram(list_, attribute):
    attributes = [ int(elem[attribute]) for elem in list_]
    #plt.hist(attributes, bins=5)
    #plt.show()
    return np.histogram(attributes, bins=5)

In [43]:
# create histograms
with open(path_users, 'r') as f:
    users_dict = json.load(f)
    users = []
    for key, val in users_dict.items():
        users.append(val)
    
    for attr in attributes:
        numbers, bins = create_histogram(users, attr)
        print (numbers, bins)
        dict_hist = {}
        dict_hist["numbers"] = numbers.tolist()
        dict_hist["bins"] = bins.tolist()
        
        with open( attr + "_hist.json", 'w') as r:
            json.dump(dict_hist, r)

[7617016     135      32       7       1] [  1.00000000e+00   1.93878000e+05   3.87755000e+05   5.81632000e+05
   7.75509000e+05   9.69386000e+05]
[7617163      21       5       1       1] [  -154.   13962.2  28078.4  42194.6  56310.8  70427. ]
[7617167      16       4       3       1] [ -3.00000000e+01   1.30096000e+04   2.60492000e+04   3.90888000e+04
   5.21284000e+04   6.51680000e+04]
[7617121      54      12       3       1] [  -154.    5383.8  10921.6  16459.4  21997.2  27535. ]
[7617152      28       9       1       1] [     0.    4285.6   8571.2  12856.8  17142.4  21428. ]
[7616913     247      24       5       2] [    0.    398.2   796.4  1194.6  1592.8  1991. ]


In [57]:
# create five classes based on reputation
class_key = "Reputation"
with open(class_key + "_hist.json", 'r') as f:
    hist = json.load(f)
    print (hist)
    num_classes = len(hist["bins"])-1
    print (num_classes)
    users_classes = np.empty((num_classes,),dtype=object)
    for i in range(users_classes.shape[0]):
        users_classes[i] = []
    print (users_classes)
    
    with open(path_users, 'r') as u:
        users_dict = json.load(u)
        for key, val in users_dict.items():
            for i in reversed(range(num_classes)):
                if int(val[class_key]) >= hist["bins"][i]:
                    users_classes[i].append(val)
                    break
    
    for class_ in users_classes:
        print (len(class_))


{'numbers': [7617016, 135, 32, 7, 1], 'bins': [1.0, 193878.0, 387755.0, 581632.0, 775509.0, 969386.0]}
5
[list([]) list([]) list([]) list([]) list([])]
7617016
135
32
7
1


In [ ]:
# TODO adapt classes (logarithmic reputation?)